### ISSUE TITLE
Functions in P accessed like global

### ISSUE THREAD

**Issue by PhoenixWhitefire** [RegularTetragon/microparsel#4]
Line 232 in microparsel.lua: the function "try" is used like a global, but it is instead a function of P. Replace with P.try()
Line 291 in microparsel.lua: the function "many" is used like a global, but it is instead a function of P. Replace with P.many()

(I don't know if this is a feature in Lua, but it doesn't work in Luau)

**Comment by RegularTetragon** [comment]
Yep, definitely a bug! I can take a look at this after work.

**Comment by RegularTetragon** [comment]
Just saw your PR actually, looked good so I went ahead and merged it
