### ISSUE TITLE
"<<" operator non-existent in Luau

### ISSUE THREAD

**Issue by PhoenixWhitefire** [RegularTetragon/microparsel#7]
json.lua contains use of "<<". The arrows don't have functionality in Luau except for less than or greater than comparisons, but there's only one of them when used for that.

**Comment by RegularTetragon** [comment]
There is a * operator intended to remind you of the fact that left bit shifting by one, i.e. << is akin to *2. The / operator corresponds to >> by contrast. These two operators should suit the same purpose in Lua 5.1 despite not being as pretty.
